// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbaccess

import (
	"database/sql"
	"time"
)

type Event struct {
	ID          int32
	Name        string
	Description sql.NullString
	StartTime   time.Time
	EndTime     time.Time
	Location    sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Ticket struct {
	ID           int32
	EventID      int32
	UserID       int32
	PurchaseDate time.Time
	SeatNumber   sql.NullString
	Price        string
	CreatedAt    sql.NullTime
}
