// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package mysql

import (
	"database/sql"
)

type Transaction struct {
	ID         int32
	SenderID   int32
	ReceiverID int32
	Amount     string
	CreatedAt  sql.NullTime
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Balance   string
	CreatedAt sql.NullTime
}
