version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: gorm_mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
