// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbaccess

import (
	"database/sql"
	"time"
)

type AdvertisementContent struct {
	ID        int64
	ShopID    int64
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FavoriteShop struct {
	UserID int64
	ShopID int64
}

type Reservation struct {
	ID                  int64
	ShopID              int64
	UserID              int64
	ReservationDatetime time.Time
	Status              string
}

type Shop struct {
	ID             int64
	Name           string
	PostalCode     string
	City           string
	Street         string
	Building       sql.NullString
	PhoneNumber    string
	BusinessHours  string
	Description    sql.NullString
	Latitude       string
	Longitude      string
	FavoritesCount sql.NullInt64
}

type ShopOwner struct {
	ID       int64
	ShopID   int64
	Name     string
	Email    string
	Password string
}

type User struct {
	ID    int64
	Name  string
	Email string
}
